// Bakes public/fonts/*.ttf into src/fontData.ts as data URIs.
// Rendering then needs no HTTP fetch for fonts at all — a tab that gets
// recreated mid-render has them immediately instead of stalling on a request.
import fs from 'fs';

const FACES = [
  ['Newsreader', 'Newsreader-Regular.ttf', 400, 'normal'],
  ['Newsreader', 'Newsreader-Medium.ttf', 500, 'normal'],
  ['Newsreader', 'Newsreader-Italic.ttf', 400, 'italic'],
  ['Onest', 'Onest-Regular.ttf', 400, 'normal'],
  ['Onest', 'Onest-SemiBold.ttf', 600, 'normal'],
  ['Onest', 'Onest-Bold.ttf', 700, 'normal'],
  ['JetBrainsMono', 'JetBrainsMono-Medium.ttf', 500, 'normal'],
];

const css = FACES.map(([family, file, weight, style]) => {
  const b64 = fs.readFileSync(`public/fonts/${file}`).toString('base64');
  return (
    `@font-face{font-family:'${family}';font-weight:${weight};` +
    `font-style:${style};font-display:block;` +
    `src:url(data:font/ttf;base64,${b64}) format('truetype');}`
  );
}).join('');

const specs = FACES.map(
  ([family, , weight, style]) =>
    `${style === 'italic' ? 'italic ' : ''}${weight} 16px ${family}`
);

fs.mkdirSync('src', { recursive: true });
fs.writeFileSync(
  'src/fontData.ts',
  '// GENERATED by scripts/build-fonts.mjs — do not edit by hand.\n' +
    `export const FONT_CSS = ${JSON.stringify(css)};\n\n` +
    `export const FONT_SPECS = ${JSON.stringify(specs, null, 2)};\n`
);

console.log(`wrote src/fontData.ts (${(css.length / 1024).toFixed(0)} KB of CSS)`);
