import { Proposal } from './api';

// Helper to generate deadline dates
const daysFromNow = (days: number): string =>
  new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();

const now = (): string => new Date().toISOString();

// Deterministic hash from proposal id (so numbers stay stable per-render, per-id)
const hashId = (id: string): number => {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = ((h << 5) - h + id.charCodeAt(i)) | 0;
  return Math.abs(h);
};

// =============================================================================
// SEED PROPOSALS - 50 Canada Proposals by Represent Civic Desk
// These are curated civic questions authored by Represent for launch content.
// Vote counts use deterministic mock data while we finalize designs.
// To return to real-only counts: set MOCK_VOTES = false below.
// =============================================================================

const MOCK_VOTES = true;

const _RAW_SEED_PROPOSALS: Proposal[] = [
  // ===========================================================================
  // GLOBAL PROPOSALS (10) — open to every Represent user, verified or not.
  // geoRestrictions: [] is the signal that a proposal is global.
  // ===========================================================================
  {
    id: 'seed-global-1',
    title: 'Binding International AI Safety Treaty',
    description: 'Establish a UN-backed treaty requiring all signatory nations to adopt baseline safety standards for frontier AI systems: pre-deployment evaluations, incident reporting, mandatory red-teaming, and a shared registry of high-capability models. Backed by an independent oversight body funded through member contributions.',
    category: 'Technology',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(21),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-2',
    title: 'Global Plastic Pollution Treaty with Production Caps',
    description: 'Support a legally binding UN treaty that caps global virgin plastic production, phases out the most harmful single-use plastics within 5 years, requires extended producer responsibility, and funds cleanup of ocean plastic through a per-tonne levy on petrochemical producers.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(18),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1440581572325-0bea30075d9d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-3',
    title: 'Universal Carbon Border Adjustment Mechanism',
    description: 'Adopt a coordinated carbon border adjustment system across major economies: imports from countries without comparable carbon pricing pay a tariff equal to the embedded emissions, with revenues reinvested in clean-energy transitions in lower-income countries.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(25),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-4',
    title: 'Pandemic Preparedness and Antimicrobial Resistance Fund',
    description: 'Create a permanent $50B/year multilateral fund for pandemic surveillance, vaccine R&D for neglected diseases, and research into next-generation antibiotics. Funded through a small levy on pharmaceutical revenues over $10B annually.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(16),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-5',
    title: 'Global Press Freedom Protection Charter',
    description: 'Establish an international charter that signatory nations commit to: protecting journalists from arbitrary detention, decriminalizing defamation, ensuring source confidentiality, and contributing to an emergency relief fund for reporters working in conflict zones or under authoritarian regimes.',
    category: 'Civil Rights',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(20),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-6',
    title: 'Orbital Sustainability and Space Debris Fees',
    description: 'Require commercial satellite operators to pay annual fees scaled to debris-creation risk, with the funds underwriting active debris-removal missions. Mandate end-of-life deorbit plans for all new launches and adopt international right-of-way rules to prevent collision cascades.',
    category: 'Technology',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(28),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-7',
    title: 'Children’s Online Safety Standards',
    description: 'Adopt a baseline international standard prohibiting algorithmic amplification of harmful content to under-16 users, requiring default-private accounts for minors, banning targeted advertising to children, and giving parents one-click data deletion.',
    category: 'Technology',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(14),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-8',
    title: 'Mental Health Parity in Public Health Systems',
    description: 'Endorse the WHO target requiring at least 10% of every member state’s public health budget be directed to mental health services, with at least half of that allocated to community-based care rather than institutional settings.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(22),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-9',
    title: 'Universal Affordable Internet Access',
    description: 'Recognize affordable broadband access as a human right and commit to closing the global connectivity gap by 2032 via shared spectrum policy, infrastructure subsidies in underserved regions, and price ceilings for entry-tier residential service relative to median income.',
    category: 'Infrastructure',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(24),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-global-10',
    title: 'Global Minimum Tax on Billionaire Wealth',
    description: 'Adopt a coordinated minimum 2% annual tax on individual net wealth above $1B, modeled on the Brazilian G20 proposal. Estimated to raise $200-250B globally per year, with revenues directed by each signatory country to climate adaptation, education, or housing.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(26),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: [],
    imageUrl: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // CANADA NATIONAL PROPOSALS (15)
  // ===========================================================================
  {
    id: 'seed-ca-1',
    title: 'National Pharmacare Program',
    description: 'Create universal prescription drug coverage providing essential medications at no cost to all Canadian residents, funded through federal health transfers and bulk purchasing agreements saving $5 billion annually.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(19),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-2',
    title: 'Ban Foreign Home Buyers Permanently',
    description: 'Make the temporary foreign buyer ban permanent for residential properties under $2 million, with exemptions only for permanent residents and refugees. Penalties include forced sale of illegally purchased properties.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(14),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-3',
    title: 'High-Speed Rail: Toronto-Montreal Corridor',
    description: 'Build dedicated high-speed rail connecting Toronto, Ottawa, and Montreal with trains reaching 300 km/h. Journey time: Toronto to Montreal in 2 hours. Estimated cost: $12 billion over 10 years.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(23),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-4',
    title: 'National Childcare Fee Cap at $10/Day',
    description: 'Expand the $10/day childcare program to all provinces and territories by 2026, with federal funding guarantees and workforce investment to create 250,000 new childcare spaces.',
    category: 'Education',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(16),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-5',
    title: 'Carbon Tax Rebate Increase',
    description: 'Double the quarterly carbon tax rebate for households while maintaining the carbon pricing system. Average family of four would receive $1,800 annually, fully offsetting fuel costs for most Canadians.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(12),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-6',
    title: 'Federal Dental Care Expansion',
    description: 'Expand the Canadian Dental Care Plan to cover all residents under $90,000 household income, including orthodontics for children and seniors\' dentures. Full implementation by 2027.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(17),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-7',
    title: 'National Housing Accelerator Fund Expansion',
    description: 'Triple the Housing Accelerator Fund to $12 billion, with bonuses for municipalities that eliminate exclusionary zoning and approve high-density housing near transit within 60 days.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(20),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-8',
    title: 'Electric Vehicle Incentive Extension',
    description: 'Extend and expand the iZEV program with $7,500 rebates for new EVs under $60,000 and $5,000 for used EVs. Include rebates for e-bikes and require 50% of new car sales be zero-emission by 2030.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(15),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-9',
    title: 'National Student Loan Forgiveness',
    description: 'Forgive up to $20,000 in federal student loans for graduates working in healthcare, education, or skilled trades in underserved communities for at least 3 years.',
    category: 'Education',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(18),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1627556704302-624286467c65?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-10',
    title: 'Indigenous Clean Water Guarantee',
    description: 'Commit $5 billion over 5 years to end all boil-water advisories on First Nations reserves permanently, with ongoing funding for water infrastructure maintenance and operator training.',
    category: 'Infrastructure',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(13),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-11',
    title: 'National Grocery Price Cap',
    description: 'Implement temporary price caps on essential groceries (bread, milk, eggs, produce) for 18 months, with excess profits taxed at 75% and redistributed as grocery rebates to low-income families.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(11),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-12',
    title: 'RCMP Body Camera Mandate',
    description: 'Require all RCMP officers to wear body cameras during interactions with the public, with automatic activation protocols and independent oversight for footage review.',
    category: 'Public Safety',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(14),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-13',
    title: 'Ban Assault-Style Weapons Buyback',
    description: 'Implement mandatory buyback of all assault-style firearms at fair market value, with amnesty period for voluntary surrender and strict penalties for non-compliance after deadline.',
    category: 'Public Safety',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(22),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-14',
    title: 'Universal Basic Income Pilot Expansion',
    description: 'Expand UBI pilots to 5 additional cities, providing $2,000/month to 10,000 participants for 3 years to study effects on employment, health, and poverty reduction.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(25),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ca-15',
    title: 'National 4-Day Work Week Trial',
    description: 'Fund a 2-year pilot program offering tax incentives to 1,000 companies that adopt a 4-day work week without reducing pay, measuring productivity, employee wellbeing, and economic impact.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(19),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada'],
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // ONTARIO PROPOSALS (6)
  // ===========================================================================
  {
    id: 'seed-on-1',
    title: 'Ontario Line Subway Acceleration',
    description: 'Fast-track the Ontario Line subway with 24/7 construction and additional funding to complete by 2030 instead of 2031. Add three new stations in underserved areas of Thorncliffe Park and Flemingdon Park.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(16),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario'],
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-on-2',
    title: 'Ontario Rent Control Restoration',
    description: 'Restore rent control to all rental units including those built after 2018, capping annual increases at 2.5% or inflation rate (whichever is lower) for the next 5 years.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(12),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario'],
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-on-3',
    title: 'Ontario Hospital Capacity Expansion',
    description: 'Build 5 new hospitals and expand 15 existing facilities, adding 3,000 beds provincewide over 7 years. Includes recruitment bonuses for nurses and fast-tracked credential recognition for internationally trained doctors.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(21),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario'],
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-on-4',
    title: 'Nuclear Energy Expansion',
    description: 'Approve construction of small modular reactors at Bruce Power and Darlington to add 4,800 MW of clean baseload power by 2035, creating 10,000 jobs and supporting grid stability for EV adoption.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(24),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario'],
    imageUrl: 'https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-on-5',
    title: 'Free Tuition for College Trades Programs',
    description: 'Eliminate tuition for all skilled trades programs at Ontario colleges, including apprenticeship costs, to address the 100,000 skilled worker shortage in construction, automotive, and manufacturing.',
    category: 'Education',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(17),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario'],
    imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-on-6',
    title: 'GO Transit All-Day Service',
    description: 'Implement 15-minute all-day GO train service on all lines, not just rush hour, with reduced fares for off-peak travel and integrated fare structure with local transit systems.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(15),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario'],
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // BRITISH COLUMBIA PROPOSALS (5)
  // ===========================================================================
  {
    id: 'seed-bc-1',
    title: 'BC Speculation Tax Expansion',
    description: 'Expand the speculation and vacancy tax provincewide (not just urban areas) and increase the rate to 3% for foreign owners and 2% for domestic speculators holding empty properties.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(14),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia'],
    imageUrl: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-bc-2',
    title: 'Old-Growth Forest Protection',
    description: 'Permanently protect all remaining old-growth forests in BC (2.7 million hectares), with $500 million transition fund for forestry workers and communities to shift to sustainable industries.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(20),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia'],
    imageUrl: 'https://images.unsplash.com/photo-1440581572325-0bea30075d9d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-bc-3',
    title: 'SkyTrain Extension to Langley',
    description: 'Accelerate the SkyTrain extension to Langley with completion by 2028, adding 8 new stations and park-and-ride facilities to reduce Highway 1 congestion and connect growing suburbs.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(18),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia'],
    imageUrl: 'https://images.unsplash.com/photo-1569074187119-c87815b476da?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-bc-4',
    title: 'BC Safe Drug Supply Program',
    description: 'Expand the safe drug supply program provincewide to combat overdose deaths, providing pharmaceutical-grade alternatives to street drugs at healthcare facilities and supervised sites.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(13),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia'],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-bc-5',
    title: 'BC Tech Sector Tax Credits',
    description: 'Introduce 30% tax credits for tech companies that hire and train local graduates, with bonuses for companies headquartering in BC and creating remote work opportunities outside Vancouver.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(16),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia'],
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // QUEBEC PROPOSALS (4)
  // ===========================================================================
  {
    id: 'seed-qc-1',
    title: 'Montreal Metro Blue Line Extension',
    description: 'Complete the long-delayed Blue Line extension to Anjou with 5 new stations, improving transit access for 300,000 residents in Montreal\'s east end. Target completion: 2029.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(19),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec'],
    imageUrl: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-qc-2',
    title: 'Quebec French Language Digital Rights',
    description: 'Require all software and digital services with over 100,000 Quebec users to offer full French interfaces, customer support, and documentation within 2 years of reaching that threshold.',
    category: 'Other',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(15),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-qc-3',
    title: 'Quebec Electric School Buses',
    description: 'Replace all 9,000 school buses in Quebec with electric models by 2030, funded by carbon credit sales and federal transit funding. Creates 2,000 manufacturing jobs at Lion Electric.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(22),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec'],
    imageUrl: 'https://images.unsplash.com/photo-1557223562-6c77ef16210f?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-qc-4',
    title: 'Quebec Healthcare Wait Time Guarantee',
    description: 'Guarantee maximum wait times for surgeries (90 days) and specialist appointments (30 days), with patients able to access private clinics at public rates if times are exceeded.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(17),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec'],
    imageUrl: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // ALBERTA PROPOSALS (3)
  // ===========================================================================
  {
    id: 'seed-ab-1',
    title: 'Alberta Green Hydrogen Hub',
    description: 'Invest $2 billion in green hydrogen production facilities using Alberta\'s wind and solar resources, creating 15,000 jobs and positioning Alberta as North America\'s clean energy leader.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(21),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-2',
    title: 'Alberta Rural Healthcare Access',
    description: 'Build 20 new rural health clinics and offer $100,000 signing bonuses for doctors committing to 5 years in underserved communities. Include telemedicine hubs in every town over 1,000 people.',
    category: 'Healthcare',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(16),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-3',
    title: 'Calgary-Edmonton Hyperloop Study',
    description: 'Fund a $50 million feasibility study for hyperloop or high-speed rail connecting Calgary and Edmonton in under 30 minutes, potentially extending to Banff for tourism.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(24),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // ALBERTA SOVEREIGNTY & SEPARATION — launch focus (Calgary/Alberta)
  // The real questions Albertans want answered directly, cutting through the
  // "referendum about whether to hold a referendum" procedural maze.
  // ===========================================================================
  {
    id: 'seed-ab-sep-1',
    title: 'Should Alberta separate from Canada?',
    description: 'The direct question, asked plainly. Hundreds of thousands of Albertans signed petitions to force a separation referendum. The courts blocked it. The province then proposed a vote on whether to even hold the vote. Skip the maze — answer the actual question here. Your ballot is identity-verified and cryptographically sealed, so the result reflects real Albertans, not bots or out-of-province noise.',
    category: 'Government',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(30),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-sep-2',
    title: 'Should Alberta hold a binding referendum on separation?',
    description: 'The procedural question the province actually put on the table: not "do you want to separate" but "do you want a vote on whether to ask the separation question." Tell your government directly whether a real, binding referendum should happen — without the legal stalling.',
    category: 'Government',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(28),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-sep-3',
    title: 'What future should Alberta pursue?',
    description: 'Separation is not a yes/no for everyone — many Albertans want a middle path. Rank or pick the direction you actually support, so the conversation reflects the real spread of opinion rather than a forced binary.',
    category: 'Government',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(30),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    voteType: 'ranked-choice',
    options: [
      'Remain in Canada as it is',
      'Stay in Canada, but negotiate far greater autonomy',
      'Hold a binding referendum on separation',
      'Separate and form an independent Alberta',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-app-1',
    title: 'Should Alberta leave the Canada Pension Plan for an Alberta Pension Plan?',
    description: 'The province has floated withdrawing from the CPP to create a standalone Alberta Pension Plan, arguing Albertans contribute more than they receive. Critics warn about the disputed asset-transfer figure and the loss of national risk-pooling. Where do you stand?',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(26),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-police-1',
    title: 'Should Alberta replace the RCMP with a provincial police force?',
    description: 'A proposal to transition policing from the federally-contracted RCMP to an Alberta Provincial Police Service. Supporters cite local accountability and faster rural response; opponents cite transition cost and disruption. Should Alberta make the switch?',
    category: 'Public Safety',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(24),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-ab-eq-1',
    title: 'Should Alberta demand renegotiation of federal equalization?',
    description: 'Alberta has long argued the federal equalization formula is unfair to the province. Should Alberta formally demand a renegotiation of equalization as a condition of remaining a full participant in federal programs?',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(22),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta'],
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // CALGARY MUNICIPAL — launch focus
  // ===========================================================================
  {
    id: 'seed-yyc-arena-1',
    title: 'Was the Scotia Place / event centre deal a good use of public money?',
    description: 'Calgary committed roughly $1.2 billion in public money toward the new Scotia Place event centre and surrounding district. Supporters point to downtown revitalization and jobs; critics question the public share of a privately-benefiting arena. Knowing what you know now, do you back the deal?',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(20),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta', 'Calgary'],
    imageUrl: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-yyc-tax-1',
    title: 'Should Calgary cap annual residential property tax increases at inflation?',
    description: 'After several years of above-inflation property tax increases, this proposal would bind City Council to keep annual residential tax hikes at or below the rate of inflation, forcing budget trade-offs to be made within that ceiling.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(18),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta', 'Calgary'],
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-yyc-rezone-1',
    title: 'Should Calgary keep blanket R-CG rezoning across established neighbourhoods?',
    description: 'Calgary adopted city-wide rezoning allowing rowhouses and multiplexes in formerly single-family areas to add housing supply. Some residents support density and affordability; others want neighbourhood-by-neighbourhood input. Should the blanket rezoning stay?',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(21),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta', 'Calgary'],
    imageUrl: 'https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // OTHER PROVINCES PROPOSALS (2)
  // ===========================================================================
  {
    id: 'seed-other-1',
    title: 'Atlantic Canada Ferry Modernization',
    description: 'Replace aging ferry fleets connecting Nova Scotia, New Brunswick, PEI, and Newfoundland with electric and hybrid vessels, reducing emissions 80% and improving reliability.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(20),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Nova Scotia'],
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-other-2',
    title: 'Prairie Agricultural Carbon Credits',
    description: 'Create a provincial carbon credit system rewarding farmers in Manitoba and Saskatchewan for regenerative agriculture practices, cover cropping, and no-till farming that sequester carbon.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(18),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Manitoba'],
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // TORONTO PROPOSALS (5)
  // ===========================================================================
  {
    id: 'seed-tor-1',
    title: 'Toronto Protected Bike Lane Network',
    description: 'Build 100 km of physically separated bike lanes connecting all neighborhoods to downtown by 2028, with secure bike parking at every TTC station and 500 new Bike Share stations.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(14),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario', 'Toronto'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-tor-2',
    title: 'Toronto Modular Housing Initiative',
    description: 'Build 5,000 modular housing units on city-owned land within 3 years using factory-built construction, providing affordable rentals at 80% of market rate for essential workers.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(17),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario', 'Toronto'],
    imageUrl: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-tor-3',
    title: 'Gardiner Expressway Removal',
    description: 'Remove the elevated Gardiner Expressway east of Jarvis Street, replacing it with an 8-lane boulevard and creating 20 hectares of new waterfront parkland and development space.',
    category: 'Infrastructure',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(25),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario', 'Toronto'],
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-tor-4',
    title: 'Toronto 24-Hour TTC Service',
    description: 'Implement 24-hour subway service on Line 1 (Yonge-University) on Fridays and Saturdays, with corresponding all-night bus service on major routes throughout the city.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(13),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario', 'Toronto'],
    imageUrl: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-tor-5',
    title: 'Toronto Commercial Vacancy Tax',
    description: 'Implement a 3% annual tax on commercial properties vacant for over 6 months to discourage landlords from keeping storefronts empty while waiting for higher rents.',
    category: 'Economy',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(16),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario', 'Toronto'],
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // VANCOUVER PROPOSALS (4)
  // ===========================================================================
  {
    id: 'seed-van-1',
    title: 'Vancouver Empty Homes Tax Increase',
    description: 'Increase the Empty Homes Tax from 3% to 5% of assessed value and close loopholes allowing owners to claim occupancy through minimal stays. Revenue funds affordable housing.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(12),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia', 'Vancouver'],
    imageUrl: 'https://images.unsplash.com/photo-1609602126247-4bbe88ce84e4?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-van-2',
    title: 'Vancouver UBC SkyTrain Extension',
    description: 'Prioritize the Millennium Line extension to UBC with completion by 2030, adding 5 stations and reducing Broadway bus overcrowding while connecting 80,000 daily campus visitors.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(19),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia', 'Vancouver'],
    imageUrl: 'https://images.unsplash.com/photo-1517732306149-e8f829eb588a?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-van-3',
    title: 'Stanley Park Vehicle-Free Sundays',
    description: 'Make Stanley Park car-free every Sunday year-round, with free shuttle service from downtown and expanded bike/scooter rentals at park entrances.',
    category: 'Environment',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(15),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia', 'Vancouver'],
    imageUrl: 'https://images.unsplash.com/photo-1609825488888-3a766db05542?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-van-4',
    title: 'Vancouver Rain City Housing Strategy',
    description: 'Fast-track 15,000 rental units by allowing 6-story buildings on all arterial roads, eliminating parking minimums near transit, and pre-approving standardized building designs.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(21),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'British Columbia', 'Vancouver'],
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // MONTREAL PROPOSALS (3)
  // ===========================================================================
  {
    id: 'seed-mtl-1',
    title: 'Montreal REM Fare Integration',
    description: 'Integrate REM fares with STM monthly passes at no extra cost, eliminating the current surcharge that makes the new transit line unaffordable for many commuters.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(11),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec', 'Montreal'],
    imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-mtl-2',
    title: 'Montreal Winter Cycling Network',
    description: 'Maintain 200 km of bike lanes year-round with priority snow clearing, heated bike shelters at major intersections, and subsidized studded tires for winter cyclists.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(18),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec', 'Montreal'],
    imageUrl: 'https://images.unsplash.com/photo-1483664852095-d6cc6870702d?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-mtl-3',
    title: 'Montreal Cultural District Protection',
    description: 'Designate the Plateau, Mile End, and St-Henri as cultural protection zones with rent stabilization for artist studios, music venues, and independent galleries facing displacement.',
    category: 'Other',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(20),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Quebec', 'Montreal'],
    imageUrl: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // CALGARY PROPOSALS (2)
  // ===========================================================================
  {
    id: 'seed-cal-1',
    title: 'Calgary Green Line LRT',
    description: 'Restore full funding for the Green Line LRT connecting North Central to Seton, with 28 stations over 46 km. Largest infrastructure project in Calgary\'s history.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(22),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta', 'Calgary'],
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=1200&fit=crop',
  },
  {
    id: 'seed-cal-2',
    title: 'Calgary Downtown Revival Fund',
    description: 'Create a $200 million fund to convert vacant downtown office towers into residential units, offering tax breaks and fast-track permits for developers adding 5,000 housing units.',
    category: 'Housing',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(17),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Alberta', 'Calgary'],
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=1200&fit=crop',
  },

  // ===========================================================================
  // OTTAWA PROPOSAL (1)
  // ===========================================================================
  {
    id: 'seed-ott-1',
    title: 'Ottawa LRT Reliability Overhaul',
    description: 'Invest $300 million in LRT system fixes including new train doors, cold-weather modifications, and redundant power systems to achieve 98% reliability. Penalize RTG for past failures.',
    category: 'Transportation',
    supportVotes: 0,
    opposeVotes: 0,
    deadline: daysFromNow(14),
    createdAt: now(),
    creatorId: 'civic-desk',
    creatorName: 'Represent Civic Desk',
    source: 'civic-desk' as const,
    geoRestrictions: ['Canada', 'Ontario', 'Ottawa'],
    imageUrl: 'https://images.unsplash.com/photo-1527684651119-a54b0ba3c587?w=800&h=1200&fit=crop',
  },
];

// Apply deterministic mock vote counts (range: 200–14,000 total per proposal,
// support ratio between 32% and 78% to avoid uniform-looking bars).
export const SEED_PROPOSALS: Proposal[] = MOCK_VOTES
  ? _RAW_SEED_PROPOSALS.map((p) => {
      const h = hashId(String(p.id));
      const total = 200 + (h % 13800);
      const supportPct = 32 + ((h >> 8) % 47);
      const supportVotes = Math.round((total * supportPct) / 100);
      const opposeVotes = total - supportVotes;
      return { ...p, supportVotes, opposeVotes };
    })
  : _RAW_SEED_PROPOSALS;

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get seed proposals filtered by user's geographic location
 * Users see: global + country + province/state + city proposals
 */
export function getSeedProposalsForGeo(
  country?: string,
  state?: string,
  city?: string
): Proposal[] {
  const userGeo = [country, state, city].filter(Boolean).map(g => g?.toLowerCase());

  return SEED_PROPOSALS.filter((proposal) => {
    const geo = proposal.geoRestrictions || [];

    // Global proposals - everyone sees
    if (geo.length === 0) return true;

    // Check hierarchical match: user must match all levels of the restriction
    // e.g., ['Canada', 'Ontario', 'Toronto'] requires user to be in Toronto
    return geo.every((restriction, index) => {
      const userLevel = userGeo[index];
      return userLevel && userLevel === restriction.toLowerCase();
    });
  });
}

/**
 * Get all seed proposals (for admin/testing)
 */
export function getAllSeedProposals(): Proposal[] {
  return SEED_PROPOSALS;
}

/**
 * Get proposal count by geographic level
 */
export function getSeedProposalStats(): {
  global: number;
  national: number;
  provincial: number;
  city: number;
  total: number;
} {
  let global = 0;
  let national = 0;
  let provincial = 0;
  let city = 0;

  SEED_PROPOSALS.forEach((p) => {
    const geo = p.geoRestrictions || [];
    if (geo.length === 0) global++;
    else if (geo.length === 1) national++;
    else if (geo.length === 2) provincial++;
    else if (geo.length === 3) city++;
  });

  return { global, national, provincial, city, total: SEED_PROPOSALS.length };
}
