import { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, ActivityIndicator, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuthStore } from '../../lib/auth';
import { useTheme } from '../../lib/theme';

const API_URL = 'https://representportal.com';
const ISSUE_TYPES = ['Law', 'Policy', 'Regulation', 'Executive Order', 'Budget Decision', 'Other'];

type AnalysisResult = { summary: string; reasoning: string; categoryScores: Array<{ category: string; score: number }>; overallVerdict: 'Aligned' | 'At Risk' | 'Violating'; flaggedPrinciples: Array<{ principleId: string; name: string; status: 'Violated' | 'Partially Violated' | 'Aligned'; explanation: string; }>; sentinelCorrections: string[]; mainProposal: string; };
type Analysis = { id: string; title: string; issueType: string; timestamp: string; analysis: AnalysisResult; };

export default function SentinelScreen() {
  const { colors } = useTheme();
  const { user } = useAuthStore();
  const [title, setTitle] = useState('');
  const [text, setText] = useState('');
  const [issueType, setIssueType] = useState('Policy');
  const [showIssueTypePicker, setShowIssueTypePicker] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [selectedAnalysis, setSelectedAnalysis] = useState<Analysis | null>(null);
  const [activeTab, setActiveTab] = useState<'summary' | 'categories' | 'findings' | 'corrections' | 'proposal'>('summary');
  const [creatingProposal, setCreatingProposal] = useState(false);
  const [proposalCreated, setProposalCreated] = useState(false);

  const handleAnalyze = async () => {
    if (!title.trim() || !text.trim()) { Alert.alert('Error', 'Please enter a title and text to analyze'); return; }
    setAnalyzing(true);
    try {
      const response = await fetch(`${API_URL}/api/sentinel/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, text, issueType }) });
      if (!response.ok) throw new Error('Analysis failed');
      const data = await response.json();
      const analysis = {
        ...data.analysis,
        categoryScores: data.analysis.categoryScores || [],
        flaggedPrinciples: data.analysis.flaggedPrinciples || [],
        sentinelCorrections: data.analysis.sentinelCorrections || [],
        mainProposal: data.analysis.mainProposal || '',
      };
      const newAnalysis: Analysis = { id: Date.now().toString(), title, issueType, timestamp: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }), analysis };
      setSelectedAnalysis(newAnalysis); setActiveTab('summary'); setTitle(''); setText('');
      Alert.alert('Analysis Complete', 'Swipe the tabs below to see Scores, Findings, Fixes, and Proposal!');
    } catch (error) { Alert.alert('Error', 'Failed to analyze document.'); }
    finally { setAnalyzing(false); }
  };

  const handleCreateProposal = async () => {
    if (!selectedAnalysis || !user?.id) { Alert.alert('Error', 'Please sign in to create a proposal'); return; }
    setCreatingProposal(true);
    try {
      const response = await fetch(`${API_URL}/api/proposals`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: selectedAnalysis.analysis.mainProposal, description: `Governance proposal generated by Sentinel analysis of: ${selectedAnalysis.title}\n\nVerdict: ${selectedAnalysis.analysis.overallVerdict}\n\nSummary: ${selectedAnalysis.analysis.summary}`, category: 'governance', geoScope: 'global', geoRestrictions: [] }) });
      if (!response.ok) throw new Error('Failed to create proposal');
      setProposalCreated(true); Alert.alert('Success', 'Your proposal has been created!');
    } catch (error) { Alert.alert('Error', 'Failed to create proposal.'); }
    finally { setCreatingProposal(false); }
  };

  const getVerdictColor = (verdict: string) => verdict === 'Aligned' ? colors.success : verdict === 'At Risk' ? colors.warning : colors.error;
  const getStatusIcon = (status: string) => status === 'Violated' ? <Ionicons name="alert-circle" size={20} color={colors.error} /> : status === 'Partially Violated' ? <Ionicons name="warning" size={20} color={colors.warning} /> : <Ionicons name="checkmark-circle" size={20} color={colors.success} />;
  const getTabLabel = (tab: string) => tab === 'summary' ? '📋 Summary' : tab === 'categories' ? '📊 Scores' : tab === 'findings' ? '🔍 Findings' : tab === 'corrections' ? '✏️ Fixes' : '📝 Proposal';

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <View style={styles.headerRow}>
          <View style={[styles.headerIcon, { backgroundColor: colors.goldLight }]}><Ionicons name="sparkles" size={24} color={colors.gold} /></View>
          <View style={{ flex: 1 }}><Text style={[styles.headerTitle, { color: colors.gold }]}>Sentinel AI</Text><Text style={[styles.headerSubtitle, { color: colors.textSecondary }]}>Governance Analyzer</Text></View>
        </View>
      </View>
      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <View style={[styles.infoCard, { backgroundColor: colors.goldLight, borderColor: colors.gold }]}>
          <Text style={[styles.infoText, { color: colors.text }]}>Sentinel evaluates government documents against 155 principles of proper human governance.</Text>
        </View>
        <View style={styles.statsRow}>
          <View style={[styles.statCard, { backgroundColor: colors.cardBg, borderColor: colors.border }]}><Text style={[styles.statValue, { color: colors.gold }]}>155</Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>Principles</Text></View>
          <View style={[styles.statCard, { backgroundColor: colors.cardBg, borderColor: colors.border }]}><Text style={[styles.statValue, { color: colors.gold }]}>11</Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>Categories</Text></View>
        </View>
        <View style={[styles.card, { backgroundColor: colors.cardBg, borderColor: colors.gold }]}>
          <View style={styles.cardHeader}><Ionicons name="document-text-outline" size={24} color={colors.gold} /><Text style={[styles.cardTitle, { color: colors.gold }]}>Submit Document</Text></View>
          <View style={styles.inputGroup}><Text style={[styles.inputLabel, { color: colors.gold }]}>Title</Text><TextInput style={[styles.input, { backgroundColor: colors.goldLight, borderColor: colors.border, color: colors.text }]} placeholder="e.g., Public Safety Act 2024" placeholderTextColor={colors.textSecondary} value={title} onChangeText={setTitle} /></View>
          <View style={styles.inputGroup}>
            <Text style={[styles.inputLabel, { color: colors.gold }]}>Issue Type</Text>
            <TouchableOpacity style={[styles.picker, { backgroundColor: colors.goldLight, borderColor: colors.border }]} onPress={() => setShowIssueTypePicker(!showIssueTypePicker)}>
              <Text style={[styles.pickerText, { color: colors.text }]}>{issueType}</Text><Ionicons name="chevron-down" size={20} color={colors.gold} />
            </TouchableOpacity>
            {showIssueTypePicker && (
              <View style={[styles.pickerDropdown, { backgroundColor: colors.cardBg, borderColor: colors.border }]}>
                {ISSUE_TYPES.map((type) => (<TouchableOpacity key={type} style={[styles.pickerOption, issueType === type && { backgroundColor: colors.goldLight }]} onPress={() => { setIssueType(type); setShowIssueTypePicker(false); }}><Text style={[styles.pickerOptionText, { color: colors.text }]}>{type}</Text></TouchableOpacity>))}
              </View>
            )}
          </View>
          <View style={styles.inputGroup}><Text style={[styles.inputLabel, { color: colors.gold }]}>Text</Text><TextInput style={[styles.textArea, { backgroundColor: colors.goldLight, borderColor: colors.border, color: colors.text }]} placeholder="Paste governance text here..." placeholderTextColor={colors.textSecondary} value={text} onChangeText={setText} multiline numberOfLines={6} textAlignVertical="top" /></View>
          <TouchableOpacity style={[styles.analyzeButton, { backgroundColor: colors.gold }, analyzing && styles.buttonDisabled]} onPress={handleAnalyze} disabled={analyzing}>
            {analyzing ? <><ActivityIndicator size="small" color="#040707" /><Text style={styles.analyzeButtonText}>Analyzing...</Text></> : <><Ionicons name="sparkles" size={20} color="#040707" /><Text style={styles.analyzeButtonText}>Analyze with Sentinel</Text></>}
          </TouchableOpacity>
        </View>

        {selectedAnalysis && (
          <View style={[styles.card, { backgroundColor: colors.cardBg, borderColor: colors.gold }]}>
            <View style={styles.analysisHeader}>
              <View style={styles.analysisHeaderLeft}><Ionicons name="checkmark-circle" size={24} color={colors.success} /><View style={{ marginLeft: 12, flex: 1 }}><Text style={[styles.cardTitle, { color: colors.gold }]}>Analysis Result</Text><Text style={[styles.analysisSubtitle, { color: colors.textSecondary }]}>{selectedAnalysis.title}</Text></View></View>
              <View style={[styles.verdictBadge, { backgroundColor: `${getVerdictColor(selectedAnalysis.analysis.overallVerdict)}20`, borderColor: getVerdictColor(selectedAnalysis.analysis.overallVerdict) }]}><Text style={[styles.verdictText, { color: getVerdictColor(selectedAnalysis.analysis.overallVerdict) }]}>{selectedAnalysis.analysis.overallVerdict}</Text></View>
            </View>
            
            <Text style={[styles.tabHint, { color: colors.textSecondary }]}>👆 Tap tabs to see all sections:</Text>
            <View style={[styles.tabsWrapper, { backgroundColor: colors.goldLight, borderColor: colors.border }]}>
              <ScrollView horizontal showsHorizontalScrollIndicator={true} contentContainerStyle={styles.tabsContent}>
                {(['summary', 'categories', 'findings', 'corrections', 'proposal'] as const).map((tab) => (
                  <TouchableOpacity key={tab} style={[styles.tab, { borderColor: colors.border, backgroundColor: activeTab === tab ? colors.gold : 'transparent' }]} onPress={() => setActiveTab(tab)}>
                    <Text style={[styles.tabText, { color: activeTab === tab ? '#000' : colors.text }]}>{getTabLabel(tab)}</Text>
                  </TouchableOpacity>
                ))}
              </ScrollView>
            </View>

            <View style={styles.tabContent}>
              {activeTab === 'summary' && (
                <View style={styles.tabPane}>
                  <View style={[styles.summaryBox, { backgroundColor: colors.goldLight, borderColor: colors.gold }]}><Text style={[styles.summaryLabel, { color: colors.gold }]}>Summary</Text><Text style={[styles.summaryText, { color: colors.text }]}>{selectedAnalysis.analysis.summary}</Text></View>
                  {selectedAnalysis.analysis.reasoning && <View style={[styles.summaryBox, { backgroundColor: colors.goldLight, borderColor: colors.border }]}><Text style={[styles.summaryLabel, { color: colors.gold }]}>Reasoning</Text><Text style={[styles.summaryText, { color: colors.text }]}>{selectedAnalysis.analysis.reasoning}</Text></View>}
                </View>
              )}
              
              {activeTab === 'categories' && (
                <View style={styles.tabPane}>
                  {selectedAnalysis.analysis.categoryScores.length === 0 ? (
                    <Text style={[styles.emptyText, { color: colors.textSecondary }]}>No category scores available</Text>
                  ) : selectedAnalysis.analysis.categoryScores.map((cat) => (
                    <View key={cat.category} style={[styles.categoryItem, { backgroundColor: colors.goldLight, borderColor: colors.border }]}>
                      <View style={styles.categoryHeader}><Text style={[styles.categoryName, { color: colors.gold }]} numberOfLines={1}>{cat.category}</Text><Text style={[styles.categoryScore, { color: colors.gold }]}>{cat.score}/100</Text></View>
                      <View style={[styles.progressBar, { backgroundColor: colors.border }]}><View style={[styles.progressFill, { width: `${cat.score}%`, backgroundColor: colors.gold }]} /></View>
                    </View>
                  ))}
                </View>
              )}
              
              {activeTab === 'findings' && (
                <View style={styles.tabPane}>
                  {selectedAnalysis.analysis.flaggedPrinciples.length === 0 ? (
                    <Text style={[styles.emptyText, { color: colors.textSecondary }]}>No flagged principles</Text>
                  ) : selectedAnalysis.analysis.flaggedPrinciples.map((flag) => (
                    <View key={flag.principleId} style={[styles.findingItem, { backgroundColor: colors.goldLight, borderColor: colors.border }]}>
                      <View style={styles.findingHeader}>
                        {getStatusIcon(flag.status)}
                        <View style={{ marginLeft: 12, flex: 1 }}>
                          <View style={styles.findingTitleRow}><Text style={[styles.principleId, { color: colors.gold }]}>{flag.principleId}</Text><Text style={[styles.statusLabel, { color: getVerdictColor(flag.status === 'Aligned' ? 'Aligned' : flag.status === 'Partially Violated' ? 'At Risk' : 'Violating') }]}>{flag.status}</Text></View>
                          <Text style={[styles.principleName, { color: colors.text }]}>{flag.name}</Text>
                          <Text style={[styles.principleExplanation, { color: colors.textSecondary }]}>{flag.explanation}</Text>
                        </View>
                      </View>
                    </View>
                  ))}
                </View>
              )}
              
              {activeTab === 'corrections' && (
                <View style={styles.tabPane}>
                  <Text style={[styles.correctionsTitle, { color: colors.gold }]}>Sentinel Corrections</Text>
                  {selectedAnalysis.analysis.sentinelCorrections.length === 0 ? (
                    <Text style={[styles.emptyText, { color: colors.textSecondary }]}>No corrections needed</Text>
                  ) : selectedAnalysis.analysis.sentinelCorrections.map((correction, i) => (
                    <View key={i} style={[styles.correctionItem, { backgroundColor: `${colors.warning}20`, borderColor: `${colors.warning}50` }]}>
                      <Text style={[styles.correctionNumber, { color: colors.warning }]}>{i + 1}</Text>
                      <Text style={[styles.correctionText, { color: colors.text }]}>{correction}</Text>
                    </View>
                  ))}
                </View>
              )}
              
              {activeTab === 'proposal' && (
                <View style={styles.tabPane}>
                  {proposalCreated ? (
                    <View style={[styles.successBox, { backgroundColor: `${colors.success}20`, borderColor: colors.success }]}>
                      <Ionicons name="checkmark-circle" size={24} color={colors.success} />
                      <View style={{ marginLeft: 12, flex: 1 }}><Text style={[styles.successTitle, { color: colors.success }]}>Proposal Created!</Text><Text style={[styles.successText, { color: colors.text }]}>Your proposal is now live for voting.</Text></View>
                    </View>
                  ) : (
                    <>
                      <View style={[styles.proposalBox, { backgroundColor: colors.goldLight, borderColor: colors.gold }]}>
                        <View style={styles.proposalHeader}><Ionicons name="document-text" size={20} color={colors.gold} /><Text style={[styles.proposalLabel, { color: colors.gold }]}>Generated Proposal</Text></View>
                        <Text style={[styles.proposalText, { color: colors.text }]}>{selectedAnalysis.analysis.mainProposal || 'No proposal generated'}</Text>
                      </View>
                      <TouchableOpacity style={[styles.createProposalButton, { backgroundColor: colors.gold }, creatingProposal && styles.buttonDisabled]} onPress={handleCreateProposal} disabled={creatingProposal}>
                        {creatingProposal ? <><ActivityIndicator size="small" color="#040707" /><Text style={styles.createProposalButtonText}>Creating...</Text></> : <><Ionicons name="add-circle" size={20} color="#040707" /><Text style={styles.createProposalButtonText}>Create Proposal</Text></>}
                      </TouchableOpacity>
                    </>
                  )}
                </View>
              )}
            </View>
          </View>
        )}
        <View style={styles.bottomPadding} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 60, paddingBottom: 16, borderBottomWidth: 1 },
  headerRow: { flexDirection: 'row', alignItems: 'center' },
  headerIcon: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  headerTitle: { fontSize: 24, fontWeight: 'bold' },
  headerSubtitle: { fontSize: 14, marginTop: 2 },
  content: { flex: 1, padding: 16 },
  infoCard: { borderRadius: 12, padding: 16, marginBottom: 16, borderWidth: 1 },
  infoText: { fontSize: 14, lineHeight: 22 },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  statCard: { flex: 1, alignItems: 'center', padding: 16, borderRadius: 12, borderWidth: 1 },
  statValue: { fontSize: 28, fontWeight: 'bold' },
  statLabel: { fontSize: 12, marginTop: 4 },
  card: { borderRadius: 16, padding: 20, marginBottom: 16, borderWidth: 1 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  cardTitle: { fontSize: 18, fontWeight: '600', marginLeft: 12 },
  inputGroup: { marginBottom: 16 },
  inputLabel: { fontSize: 14, fontWeight: '600', marginBottom: 8 },
  input: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16 },
  textArea: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, minHeight: 120 },
  picker: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  pickerText: { fontSize: 16 },
  pickerDropdown: { borderWidth: 1, borderRadius: 10, marginTop: 8, overflow: 'hidden' },
  pickerOption: { paddingHorizontal: 16, paddingVertical: 14 },
  pickerOptionText: { fontSize: 16 },
  analyzeButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 30, gap: 8, marginTop: 8 },
  analyzeButtonText: { fontSize: 16, fontWeight: '600', color: '#040707' },
  buttonDisabled: { opacity: 0.6 },
  analysisHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  analysisHeaderLeft: { flexDirection: 'row', flex: 1 },
  analysisSubtitle: { fontSize: 12, marginTop: 2 },
  verdictBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1 },
  verdictText: { fontSize: 12, fontWeight: '600' },
  tabHint: { fontSize: 13, marginBottom: 8, fontStyle: 'italic' },
  tabsWrapper: { borderRadius: 12, padding: 8, marginBottom: 16, borderWidth: 1 },
  tabsContent: { gap: 8, paddingRight: 8 },
  tab: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20, borderWidth: 1 },
  tabText: { fontSize: 13, fontWeight: '600' },
  tabContent: { minHeight: 200 },
  tabPane: {},
  emptyText: { fontSize: 14, textAlign: 'center', paddingVertical: 20 },
  summaryBox: { borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1 },
  summaryLabel: { fontSize: 14, fontWeight: '600', marginBottom: 8 },
  summaryText: { fontSize: 14, lineHeight: 22 },
  categoryItem: { borderRadius: 12, padding: 16, marginBottom: 10, borderWidth: 1 },
  categoryHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  categoryName: { fontSize: 13, fontWeight: '500', flex: 1, marginRight: 8 },
  categoryScore: { fontSize: 13, fontWeight: '600' },
  progressBar: { height: 6, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 3 },
  findingItem: { borderRadius: 12, padding: 16, marginBottom: 10, borderWidth: 1 },
  findingHeader: { flexDirection: 'row' },
  findingTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  principleId: { fontSize: 11, fontWeight: '600', marginRight: 8 },
  statusLabel: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
  principleName: { fontSize: 15, fontWeight: '600', marginBottom: 4 },
  principleExplanation: { fontSize: 13, lineHeight: 20 },
  correctionsTitle: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  correctionItem: { flexDirection: 'row', borderRadius: 12, padding: 16, marginBottom: 10, borderWidth: 1 },
  correctionNumber: { fontSize: 16, fontWeight: 'bold', marginRight: 12 },
  correctionText: { fontSize: 14, lineHeight: 22, flex: 1 },
  proposalBox: { borderRadius: 12, padding: 16, marginBottom: 16, borderWidth: 1 },
  proposalHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  proposalLabel: { fontSize: 16, fontWeight: '600', marginLeft: 8 },
  proposalText: { fontSize: 15, lineHeight: 24 },
  createProposalButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 30, gap: 8 },
  createProposalButtonText: { fontSize: 16, fontWeight: '600', color: '#040707' },
  successBox: { flexDirection: 'row', borderRadius: 12, padding: 16, borderWidth: 1 },
  successTitle: { fontSize: 16, fontWeight: '600', marginBottom: 4 },
  successText: { fontSize: 14, lineHeight: 20 },
  bottomPadding: { height: 100 },
});
